# Generated by Django 4.0.5 on 2022-06-10 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import schemas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[("'", "Single-quote (')"), ('"', 'Double-quote (")')], default='"', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ready'), (1, 'Processing')], default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=schemas.models.dataset_path)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('Full name', 'Full Name'), ('Job', 'Job'), ('Email', 'Email'), ('Integer', 'Integer')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
